version: "3.8"
name: zephon
services:
  postgres:
    image: postgres:latest
    container_name: zephon-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: zephon
      POSTGRES_PASSWORD: zephonpassword
      POSTGRES_DB: eventmakerdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
